;;; -*- Mode: Common-lisp; Package: Natsoft; Readtable: Joshua -*

(DEFDATA-TYPE |java.util.Vector| :SUPER-TYPES (SEQUENCE)) 
(DEFTASK CAMERA :SUPER-TYPES (INPUT-DEVICE) :INTERFACE ((:INPUTS) (:OUTPUTS (DATA (STREAM IMAGE))))) 
(DEFTASK CAMERA :SUPER-TYPES (INPUT-DEVICE) :INTERFACE ((:INPUTS) (:OUTPUTS (DATA (STREAM IMAGE))))) 